name: Continuous Integration Workflow

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        
    - name: Install dependencies
      run: composer install
        
    - name: Run linter
      run: ./vendor/bin/phpcs --standard=PSR12 src/
      
    - name: Run tests
      run: ./vendor/bin/phpunit
